### ISSUE TITLE
NS record issue

### ISSUE THREAD

**Issue by isatis123** [gclayburg/synology-diskstation-scripts#15] opened 2016-09-03 11:37 UTC
Hello all,
First, thank you for these scripts!
Everything is working properly but each time that an update is done, all my NS records are deleted. 
How can I fix this issue?

**Comment by gclayburg** [comment] 2016-09-17 17:52
This has been reported a few times.  I'm on it.

**Comment by gclayburg** [comment] 2016-09-17 17:57
duplicate of #11

**Comment by gclayburg** [comment] 2016-09-17 18:24
@isatis123 Actually, your issue might be different than #11 .  could you post a sample of your DNS forward and reverse files that have a problem?

**Comment by gclayburg** [comment] 2017-03-07 00:15
closing for lack of activity.  If there is still a problem, please open a new issue.

**Closed by gclayburg** 2017-03-07 00:15 UTC
